/**
 * Game balance and tuning parameters
 */

module.exports = {
  // Age progression
  MATCHES_PER_AGE_INCREASE: 20,
  
  // Training
  TRAINING_STAT_INCREASE_MIN: 1,
  TRAINING_STAT_INCREASE_MAX: 3,
  TRAINING_STATS_TO_IMPROVE_MIN: 1,
  TRAINING_STATS_TO_IMPROVE_MAX: 2,
  TRAINING_STAMINA_DECREASE_MIN: 10,
  TRAINING_STAMINA_DECREASE_MAX: 20,
  TRAINING_FORM_INCREASE_MIN: 1,
  TRAINING_FORM_INCREASE_MAX: 2,
  TRAINING_INJURY_CHANCE: 5,
  
  // Rest
  REST_STAMINA_RECOVERY_MIN: 30,
  REST_STAMINA_RECOVERY_MAX: 50,
  REST_FORM_INCREASE_MIN: 1,
  REST_FORM_INCREASE_MAX: 2,
  
  // Match
  MATCH_STAMINA_DECREASE_MIN: 15,
  MATCH_STAMINA_DECREASE_MAX: 25,
  MATCH_FORM_BASE_DECREASE: 1,
  MATCH_INJURY_CHANCE: 2,
  MATCH_PERFORMANCE_RANDOM_MIN: -5,
  MATCH_PERFORMANCE_RANDOM_MAX: 5,
  MATCH_PERFORMANCE_OVERALL_WEIGHT: 0.6,
  MATCH_PERFORMANCE_FORM_WEIGHT: 0.2,
  MATCH_PERFORMANCE_STAMINA_DIVISOR: 10,
  
  // Form
  FORM_MIN: -10,
  FORM_MAX: 10,
  FORM_MATCH_BONUS_GOAL: 2,
  FORM_MATCH_BONUS_ASSIST: 1,
  FORM_MATCH_BONUS_RATING: 0.5, // per rating point above 7
  
  // Stamina
  STAMINA_MIN: 0,
  STAMINA_MAX: 100,
  STAMINA_TRAIN_THRESHOLD: 20,
  STAMINA_MATCH_THRESHOLD: 30,
  
  // Aging
  AGING_START_AGE: 30,
  AGING_PHYSICAL_DECREASE_PER_YEAR: 1,
  
  // Market value
  VALUE_BASE_MULTIPLIER: 0.1,
  VALUE_AGE_PEAK: 28,
  VALUE_AGE_DECLINE_START: 28,
  VALUE_AGE_DECLINE_RATE: 0.05, // per year after peak
  VALUE_FORM_MULTIPLIER: 0.02, // per form point
  
  // Match rating
  RATING_MIN: 1,
  RATING_MAX: 10,
  RATING_BASE: 5,
  RATING_PERFORMANCE_MULTIPLIER: 0.1,
  
  // Goals and assists
  GOAL_BASE_CHANCE: 0.15, // base chance per match
  ASSIST_BASE_CHANCE: 0.20, // base chance per match
  GOAL_PERFORMANCE_MULTIPLIER: 0.02,
  ASSIST_PERFORMANCE_MULTIPLIER: 0.015,
  
  // Transfer offers
  OFFER_GENERATION_CHANCE: 15, // % chance after good match performance
  OFFER_EXPIRY_DAYS: 7, // Days until offer expires
  OFFER_SALARY_MULTIPLIER_MIN: 0.8,
  OFFER_SALARY_MULTIPLIER_MAX: 1.5,
  OFFER_CONTRACT_LENGTH_MIN: 2,
  OFFER_CONTRACT_LENGTH_MAX: 5,
  OFFER_SIGNING_BONUS_MULTIPLIER: 0.1, // Based on salary
  
  // Season
  SEASON_LENGTH: 20, // Matches per season
  
  // Difficulty scaling
  DIFFICULTY_BASE: 0,
  DIFFICULTY_OVERALL_MULTIPLIER: 0.02,
  DIFFICULTY_TIER_MULTIPLIER: 5,
  DIFFICULTY_CAREER_STAGE_MULTIPLIER: 2,
  
  // Form decay
  FORM_DECAY_RATE_BASE: 0.1, // Per match
  FORM_DECAY_RATE_TIER_MULTIPLIER: 0.05, // Additional per tier
  
  // Enhanced injuries
  INJURY_SEVERITY_MINOR_CHANCE: 60, // % of injuries that are minor
  INJURY_SEVERITY_MODERATE_CHANCE: 30, // % of injuries that are moderate
  INJURY_SEVERITY_SEVERE_CHANCE: 10, // % of injuries that are severe
  INJURY_MINOR_MATCHES: { min: 1, max: 2 },
  INJURY_MODERATE_MATCHES: { min: 3, max: 5 },
  INJURY_SEVERE_MATCHES: { min: 6, max: 10 }
};

